title: Blog
email: minhlocle08@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: '/blog'
url: ''
twitter_username: jekyllrb
github_username: jekyll
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
